export const t = {
  common: {
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    add: "Add",
    title: "Title",
    description: "Description",
    amount: "Amount",
    notes: "Notes",
    status: "Status",
    none: "None",
    select: "Select",
    success: "Success",
    error: "Error",
    search: "Search",
    loading: "Loading...",
    quantity: "Quantity",
    additionalInfo: "Additional Information",
    purpose: "Purpose",
    comments: "Comments",
    accounts: "Accounts",
    unknown: "Unknown",
    optional: "optional",
    selectHolder: "Select Holder",
    selectAssetPurpose: "Select Asset Purpose",
    selectGoal: "Select Goal (Optional)",
    selectIncomeSource: "Select Income Source (Optional)",
    selectLoanType: "Select Loan Type",
    selectInsuranceType: "Select Insurance Type",
    selectSipType: "Select SIP Type",
    selectSwpBucket: "Select SWP Bucket",
    selectAssetClass: "Select Asset Class",
    selectAssetSubClass: "Select Asset Sub Class",
  },
  dashboard: {
    title: "Financial Dashboard",
    totalAssets: "Total Assets",
    totalLiabilities: "Total Liabilities",
    netWorth: "Net Worth",
    monthlyIncomeVsExpenses: "Monthly Income vs Expense Categories vs 50:30:20 Rule",
    financialGoalsProgress: "Financial Goals Progress",
    monthlyCashFlow: "Monthly Cash Flow (Savings)",
    assetAllocationClass: "Asset Allocation by Class",
    projectedGrowth: "Projected Asset Growth (1 Year)",
    assetAllocationBucket: "Asset Allocation by Buckets",
    assetAllocationGoal: "Asset Allocation by Goal",
    incomeBreakdown: "Income Breakdown",
    reitsSimulator: "REITs Simulator",
    swpCalculator: "SWP Calculator",
    commodityRates: "Commodity Rates",
  },
  settings: {
    title: "System Settings",
    appearance: "Appearance",
    theme: "Theme",
    themeSubtitle: "Instantly skin the entire interface with a dynamic preset theme.",
    currency: "Base Currency",
    currencySubtitle: "Select your primary currency. The entire platform will format values to match.",
    pwaUpdates: "Application Updates",
    pwaUpdatesSubtitle: "Check for new versions and manage software updates.",
    currentVersion: "Current Version",
    checking: "Checking...",
    checkedLatest: "✓ Checked! Already on the latest version.",
    updateAvailable: "New update available!",
    checkForUpdate: "Check for Updates",
    takeUpdate: "Update Now",
    general: "General",
    database: "Database",
    importExport: "Import & Export",
    backupRestore: "Backup & Restore",
  },
  upcomingExpenses: {
    title: "Upcoming Expenses",
    addExpense: "Add Upcoming Expense",
    editExpense: "Edit Upcoming Expense",
    expenseTitle: "Title",
    expenseTitlePlaceholder: "What is this expense for?",
    dueDate: "Due Date",
    completed: "Mark as Completed",
    totalPending: "Total Pending",
    byPurpose: "By Purpose",
    noPending: "No pending expenses",
  },
  assets: {
    title: "Asset Holdings",
    addAsset: "Add Asset Holding",
    editAsset: "Edit Asset Holding",
    class: "Class",
    selectClass: "Select Class",
    subClass: "Sub Class",
    selectSubClass: "Select Sub Class",
    marketLink: "Market Link",
    linkToMarket: "Link to Market Data",
    purity: "Purity",
    grams: "Grams",
    existingAllocation: "Existing Allocation (Value)",
    goal: "Goal",
    holder: "Holder",
    selectHolder: "Select Holder",
    detail: "Detail",
    sipAmount: "SIP Amount",
    sipType: "SIP Type",
    selectSipType: "Select SIP Type",
    swpBucket: "SWP Bucket",
    selectSwpBucket: "Select SWP Bucket",
    noneManualEntry: "None (Manual Entry)",
    gold: "Gold",
    gold24k: "24K (99.9%)",
    gold22k: "22K (91.6%)",
    selectLinkType: "Select Link Type",
    selectPurity: "Select Purity",
    autoCalculatedText: "Auto-calculated based on market rate",
    unknownClass: "Unknown Class",
  },
  goals: {
    title: "Financial Goals",
    addGoal: "Add Financial Goal",
    editGoal: "Edit Financial Goal",
    goalName: "Goal Name",
    priority: "Priority",
    durationYears: "Duration (Years)",
    targetToday: "Target Amount Required Today",
    allocated: "Allocated",
    target: "Target",
    gap: "Gap",
    progress: "Progress",
  },
  liabilities: {
    title: "Liabilities",
    addLiability: "Add Liability",
    editLiability: "Edit Liability",
    loanType: "Loan Type",
    selectLoanType: "Select Loan Type",
    loanAmount: "Loan Amount (Initial Principal)",
    startDate: "Start Date",
    durationMonths: "Duration (Months)",
    outstandingBalance: "Outstanding Balance",
    monthlyEmi: "Monthly EMI",
    emi: "EMI",
    totalLiabilities: "Total Liabilities",
    totalMonthlyEmi: "Total Monthly EMI",
  },
  income: {
    title: "Income Sources",
    addIncome: "Add Income Source",
    editIncome: "Edit Income Source",
    incomeSource: "Income Source",
    holder: "Holder",
    monthlyAmount: "Monthly Amount",
    totalMonthly: "Total Monthly Income",
  },
  cashFlow: {
    title: "Monthly Cash Flow",
    addFlow: "Add Cash Flow",
    editFlow: "Edit Cash Flow",
    flowItem: "Flow Item / Purpose",
    monthlyAmount: "Monthly Amount",
    goalLink: "Goal Link",
    incomeLink: "Income Link (Source)",
    transferFrom: "Transfer From (Account)",
    toAccount: "To Account",
    assetPurpose: "Asset Purpose",
    allocationGap: "Allocation Gap?",
    totalInflow: "Total Income Inflow",
    totalOutflow: "Total Outflow Expenses",
    netSavings: "Net Savings Cash Flow",
    breakdownTitle: "Cash Flow Breakdown",
    unassignedSource: "Unassigned Source",
    unknownBank: "Unknown Bank",
    unknown: "Unknown",
    unknownGoal: "Unknown Goal",
  },
  keywords: {
    need: "Need",
    want: "Want",
    saving: "Saving",
    emergency: "Emergency Fund",
    retirement: "Retirement",
    education: "Education",
    marriage: "Marriage",
    equity: "Equity",
    stock: "Stock",
    debt: "Debt",
    liquid: "Liquid",
    gold: "Gold",
    bitcoin: "Bitcoin",
    commodity: "Commodity",
    reit: "REIT",
    realEstate: "Real Estate",
    sip: "SIP",
    mutualFund: "Mutual Fund",
    fd: "Fixed Deposit",
    epf: "EPF",
    ssy: "SSY",
    income: "Income",
    salary: "Salary",
    expense: "Expense",
    emi: "EMI",
    insurance: "Insurance",
    donation: "Donation",
    loan: "Loan",
    liability: "Liability",
    shortTerm: "Short Term",
    longTerm: "Long Term",
    unknown: "Unknown",
  },
  nav: {
    dashboard: "Dashboard",
    cashFlow: "Cash Flow",
    income: "Income",
    monthlyCashFlow: "Monthly Cash Flow",
    upcomingExpenses: "Upcoming Expenses",
    portfolio: "Portfolio",
    assets: "Assets",
    liabilities: "Liabilities",
    insurances: "Insurances",
    planning: "Planning",
    fire: "FIRE",
    goals: "Goals",
    networthProjection: "Networth Projection",
    settingsInfo: "Settings & Info",
    tools: "Tools",
    knowledgeCentre: "Knowledge Centre",
    settings: "Settings",
    about: "About",
    updateAvailable: "Update Available",
    signOut: "Sign out",
  },
  driveSync: {
    successConnect: "✅ Successfully connected to Google Drive and synced!",
    failConnect: "❌ Failed to connect to Google Drive: ",
    successSync: "✅ Successfully synced local data to Google Drive",
    failSync: "❌ Failed to sync to Google Drive",
    checking: "Checking Google Drive connection...",
    syncing: "Syncing with Google Drive...",
    connectedAs: "Sync to Google Drive (Connected as {name})",
    connectAndSync: "Connect Google Drive & Sync Local Data",
    connecting: "Connecting...",
    syncingShort: "Syncing...",
    synced: "Synced",
    failed: "Failed",
    cloudSync: "Cloud Sync",
    backupSetup: "Backup Setup",
    notConnectedTip: "Not connected to Cloud Sync",
  },
  financialFreedom: {
    title: "Financial Freedom Tracker",
    currentLevel: "Current Level",
    completed: "Completed",
    inProgress: "In Progress",
    locked: "Locked",
    criteriaMet: "Criteria Met",
    targetNotMet: "Target not met",
    remaining: "Remaining",
    progress: "Progress",
    target: "Target",
    noteLabel: "Note",
    downloadLabel: "Download as Markdown",
    levels: {
      clarity: {
        label: "Clarity",
        desc: "Knowing where you stand",
        criteria: "Track Income & Expenses",
        tracking: "Tracking",
        notTracking: "Not Tracking",
        currentLabel: "Income & Expenses",
      },
      solvency: {
        label: "Solvency",
        desc: "Income > Expenses",
        criteria: "Monthly Income > Expenses",
        currentLabel: "Income vs Expenses",
      },
      breathingRoom: {
        label: "Breathing Room",
        desc: "Positive Net Worth",
        criteria: "Assets > Liabilities",
        currentLabel: "Assets vs Liabilities",
      },
      stability: {
        label: "Stability",
        desc: "3 Months Emergency Fund",
        criteria: "Emergency Fund > 3x Expenses",
        currentLabel: "Emergency Fund vs 3x Needs",
      },
      flexibility: {
        label: "Flexibility",
        desc: "6 Months Emergency Fund",
        criteria: "Emergency Fund > 6x Expenses",
        currentLabel: "Emergency Fund vs 6x Needs",
      },
      leanFire: {
        label: "Lean FIRE",
        desc: "Assets cover Needs (3.5% Rule)",
        criteria: "Investments > 343x (Needs - EMI)",
        note: "EMI is deducted because we assume you already have enough assets to repay the loan. The calculation only considers Retirement Assets, excluding other goal-linked assets.",
        currentLabel: "Retirement Assets vs 3.5% SWR Lean FIRE Target",
      },
      independence: {
        label: "Financial Independence",
        desc: "Assets cover Needs & Wants (3.5% Rule)",
        criteria: "Investments > 343x (Needs - EMI + Wants)",
        note: "EMI is deducted because we assume you already have enough assets to repay the loan. The calculation only considers Retirement Assets, excluding other goal-linked assets.",
        currentLabel: "Retirement Assets vs 3.5% SWR Target",
      },
      abundantWealth: {
        label: "Abundant Wealth",
        desc: "Unlimited options",
        criteria: "Investments > 600x (Needs - EMI + Wants)",
        note: "EMI is deducted because we assume you already have enough assets to repay the loan. The calculation only considers Retirement Assets, excluding other goal-linked assets.",
        currentLabel: "Retirement Assets vs 50x Annual Needs",
      }
    }
  }
};
export type LocaleType = typeof t;
